[package]
name = "stackyy"
version = "0.1.0"
edition = "2021"
description = "The Stackyy-Lang VM/Compiler/Interpreter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"]}
backtrace = "*"